sudo: required

services: docker

# Build the files
install:
  - docker-compose run hugo hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  fqdn: developers.designmynight.com
  # local_dir: /
  github_token: $GITHUB_TOKEN
  target_branch: docker
  on:
    branch: docker #TODO: Change to master