languageCode = "en-gb"
title = "DMN developer documentation"
theme = "hugo-material-docs"
publishDir = "../blog-dist"
baseURL = "http://developers.designmynight.com/"
metadataformat = "yaml"
canonifyurls = false
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-12385609-13"

[params]
	# General information
	author = "DesignMyNight Tech Team"
	description = "Developer documentation for DesignMyNight"
	copyright = "DesignMyNight"

	# Repository
	provider = ""
	repo_url = ""

	version = "1.1.0"
	logo = "images/logo.png"
	favicon = "images/favicon.png"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "teal"
    	accent  = "deep purple"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	twitter = ""
	github  = "designmynight/dmn-developers"

[[menu.main]]
	name   = "Introduction"
	url    = "/"
	weight = 1

[[menu.main]]
    weight = 99
    name = "    "

[[menu.main]]
    name   = "Widgets"
    url    = "widgets/"
    identifier = "widgets"
	weight = 100

[[menu.main]]
	name   = "Booking widget"
	url    = "widgets/booking-widget/"
	parent = "widgets"
	weight = 101

[[menu.main]]
	name   = "Ticket widget"
	url    = "widgets/ticket-widget/"
	parent = "widgets"
	weight = 102

[[menu.main]]
    weight = 199
    name = " "

[[menu.main]]
    name   = "Collins Onboarding"
    url    = "collins-onboarding/"
    identifier = "collins-onboarding"
	weight = 200
	
[[menu.main]]
	name   = "Updating Email Settings"
	url    = "collins-onboarding/updating-email-settings/"
	parent = "collins-onboarding"
	weight = 201
	
[[menu.main]]
	name   = "Collins Booking Widget"
	url    = "collins-onboarding/booking-widget/"
	parent = "collins-onboarding"
	weight = 202
	
[[menu.main]]
	name   = "Customising 2nd Iframe"
	url    = "collins-onboarding/customising-2nd-iframe/"
	parent = "collins-onboarding"
	weight = 203

[[menu.main]]
	name   = "Booking URLs"
	url    = "collins-onboarding/booking-url/"
	parent = "collins-onboarding"
	weight = 204
	
[[menu.main]]
	name   = "General Enquiry Form"
	url    = "collins-onboarding/general-enquiry-form/"
	parent = "collins-onboarding"
	weight = 205
	
[[menu.main]]
	name   = "Customising Email Templates"
	url    = "collins-onboarding/customising-email-templates/"
	parent = "collins-onboarding"
	weight = 206
	
[[menu.main]]
	name   = "Taking Bookings from Google"
	url    = "collins-onboarding/taking-bookings-from-google/"
	parent = "collins-onboarding"
	weight = 207

[[menu.main]]
	name   = "Tracking"
	url    = "collins-onboarding/tracking/"
	parent = "collins-onboarding"
	weight = 208


[[menu.main]]
    weight = 299
    name = " "

[[menu.main]]
    name   = "API"
    url    = "api/"
    identifier = "API"
	weight = 300

[[menu.main]]
	name   = "API Basics"
	url    = "api/api-basics/"
	weight = 301
	parent = "API"

[[menu.main]]
	name   = "Booking API"
	url    = "api/booking-api/"
	weight = 302
	parent = "API"

[[menu.main]]
	name   = "Bookings search"
	url    = "api/bookings-search/"
	weight = 303
	parent = "API"

[[menu.main]]
    name   = "Users API"
    url    = "api/users-api/"
    weight = 304
	parent = "API"

[[menu.main]]
	name   = "Offers API"
	url    = "api/offers-api/"
	weight = 305
	parent = "API"

[[menu.main]]
	name   = "Venue Groups API"
	url    = "api/venue-groups/"
	weight = 306
	parent = "API"

[[menu.main]]
	name   = "Event Guests API"
	url    = "api/event-guests-api/"
	weight = 307
	parent = "API"

[[menu.main]]
	name   = "API FAQs"
	url    = "api/api-faqs/"
	weight = 308
	parent = "API"

[[menu.main]]
    weight = 399
    name = "        "

[[menu.main]]
    name   = "EPOS/CRM Integrations"
    url    = "epos-crm-integrations/"
    identifier = "epos-crm-integrations"
	weight = 400

[[menu.main]]
    name   = "Zonal EPOS Integration"
    url    = "epos-crm-integrations/zonal-epos-integration/"
    parent = "epos-crm-integrations"
	weight = 401

[[menu.main]]
    name   = "IBS EPOS Integration"
    url    = "epos-crm-integrations/ibs-epos-integration/"
    parent = "epos-crm-integrations"
	weight = 402

[[menu.main]]
    name   = "CRM Integration"
    url    = "epos-crm-integrations/crm-integration/"
    parent = "epos-crm-integrations"
	weight = 403

[[menu.main]]
    weight = 499
    name = "          "


[[menu.main]]
    weight = 599
    name = "            "

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
